### ISSUE TITLE
If the obscene word is at the beginning the censoring is not recovered

### ISSUE THREAD

**Issue by vonbv** [jo3-l/obscenity#69]
### Expected behavior

Typing "fu" censors the word into "**" but continuing on to typing "funtastic" yields a "**ntastic". It's similar to "as" filtering to "**" but having "assembly" yields "**sembly". 

### Actual behavior

**ntastic 

### Node.js version

v20.11.1

### Obscenity version

v0.3.1

### Priority

- [ ] Low
- [ ] Medium
- [X] High

### Terms

- [X] I agree to follow the project's Code of Conduct.
- [X] I have searched existing issues for similar reports.

**Comment by jo3-l** [comment]
Thanks for the report, but it's not at all clear what the actual issue is from your description. Can you provide a minimal reproducible example and explicitly identify the actual versus expected output?

Note that with the default datatest, neither of the strings `funtastic` nor `assembly` contain any matches.

**Comment by jo3-l** [comment]
Per my previous comment, this issue is not actionable as is. Given the lack of response, I am closing off this issue for now but would be happy to reopen and investigate further if more detail is provided. Thanks.
